// PROTOTYPE (throwaway, #233) — a small catalog of real Paizo Spells (CRB,
// plus the APG summoner and UM magus levels where they matter for a Spell
// Effect's pre-fill), shaped like the data model's `spell` Catalog Entries.
// Levels per class tag follow the Foundry `learnedAt.class` convention:
// arcanist = wizard = sorcerer, oracle = cleric. Only the class tags in
// `ClassTag` are listed; a missing tag means "not on that list" here.
// Domain and bloodline levels are the `learnedAt` domain/bloodline lists.

import type { CatalogEntry, ClassTag, SchoolKey, SpellDetail } from './types';

type Levels = Partial<Record<ClassTag, number>>;

/** Sorcerer/wizard (and the arcanist, which shares the list). */
const sw = (n: number): Levels => ({ sorcerer: n, wizard: n, arcanist: n });
/** Cleric (and the oracle, which shares the list). */
const co = (n: number): Levels => ({ cleric: n, oracle: n });

function spell(
  slug: string,
  name: string,
  school: SchoolKey,
  levels: Levels,
  summary: string,
  opts: {
    domain?: Record<string, number>;
    bloodline?: Record<string, number>;
    subschools?: string[];
    descriptors?: string[];
  } = {},
): CatalogEntry {
  const grantedLevels: SpellDetail['grantedLevels'] = {};
  if (opts.domain) grantedLevels.domain = opts.domain;
  if (opts.bloodline) grantedLevels.bloodline = opts.bloodline;
  return {
    key: `spell.${slug}`,
    scope: 'global',
    name,
    summary,
    stacksWithItself: false,
    modifiers: [],
    detail: {
      kind: 'spell',
      levels,
      grantedLevels,
      school,
      subschools: opts.subschools ?? [],
      descriptors: opts.descriptors ?? [],
    },
  };
}

export const SPELLS: CatalogEntry[] = [
  // ------------------------------------------------------------ 0-level
  spell(
    'acidSplash',
    'Acid splash',
    'conjuration',
    { ...sw(0), magus: 0, summoner: 0 },
    'Orb deals 1d3 acid damage',
    { subschools: ['creation'], descriptors: ['acid'] },
  ),
  spell(
    'bleed',
    'Bleed',
    'necromancy',
    { ...sw(0), ...co(0) },
    'A stabilized creature resumes dying',
  ),
  spell(
    'createWater',
    'Create water',
    'conjuration',
    { ...co(0), druid: 0 },
    'Creates 2 gallons/level of pure water',
    { subschools: ['creation'], descriptors: ['water'] },
  ),
  spell(
    'daze',
    'Daze',
    'enchantment',
    { ...sw(0), bard: 0 },
    'A humanoid of 4 HD or less loses its next action',
    { subschools: ['compulsion'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'detectMagic',
    'Detect magic',
    'divination',
    { ...sw(0), ...co(0), bard: 0, druid: 0, magus: 0, summoner: 0 },
    'Detects spells and magic items within 60 ft.',
  ),
  spell(
    'disruptUndead',
    'Disrupt undead',
    'necromancy',
    { ...sw(0), magus: 0 },
    'Deals 1d6 damage to one undead',
  ),
  spell(
    'guidance',
    'Guidance',
    'divination',
    { ...co(0), druid: 0 },
    '+1 on one attack roll, saving throw or skill check',
  ),
  spell(
    'light',
    'Light',
    'evocation',
    { ...sw(0), ...co(0), bard: 0, druid: 0, magus: 0, summoner: 0 },
    'Object shines like a torch',
    { descriptors: ['light'] },
  ),
  spell(
    'mageHand',
    'Mage hand',
    'transmutation',
    { ...sw(0), bard: 0, magus: 0, summoner: 0 },
    '5-pound telekinesis',
  ),
  spell(
    'prestidigitation',
    'Prestidigitation',
    'universal',
    { ...sw(0), bard: 0, magus: 0, summoner: 0 },
    'Performs minor tricks',
  ),
  spell(
    'rayOfFrost',
    'Ray of frost',
    'evocation',
    { ...sw(0), magus: 0 },
    'Ray deals 1d3 cold damage',
    { descriptors: ['cold'] },
  ),
  spell(
    'readMagic',
    'Read magic',
    'divination',
    { ...sw(0), ...co(0), bard: 0, druid: 0, magus: 0, paladin: 1, ranger: 1 },
    'Read scrolls and spellbooks',
  ),
  spell(
    'resistance',
    'Resistance',
    'abjuration',
    { ...sw(0), ...co(0), bard: 0, druid: 0, paladin: 1 },
    '+1 on saving throws',
  ),
  spell(
    'stabilize',
    'Stabilize',
    'conjuration',
    { ...co(0), druid: 0 },
    'A dying creature stabilizes',
    { subschools: ['healing'] },
  ),
  spell(
    'virtue',
    'Virtue',
    'transmutation',
    { ...co(0), druid: 0, paladin: 1 },
    'Subject gains 1 temporary hp',
  ),
  // ------------------------------------------------------------ 1st
  spell(
    'bless',
    'Bless',
    'enchantment',
    { ...co(1), paladin: 1 },
    'Allies gain +1 on attack rolls and saves against fear',
    {
      domain: { Community: 1 },
      subschools: ['compulsion'],
      descriptors: ['mind-affecting'],
    },
  ),
  spell(
    'blessWeapon',
    'Bless weapon',
    'transmutation',
    { paladin: 1 },
    'Weapon strikes true against evil foes',
  ),
  spell(
    'burningHands',
    'Burning hands',
    'evocation',
    { ...sw(1), magus: 1 },
    '1d4/level fire damage in a 15-ft. cone',
    { domain: { Fire: 1 }, descriptors: ['fire'] },
  ),
  spell(
    'calmAnimals',
    'Calm animals',
    'enchantment',
    { druid: 1, ranger: 1 },
    'Calms 2d4 + level HD of animals',
    {
      domain: { Animal: 1 },
      subschools: ['compulsion'],
      descriptors: ['mind-affecting'],
    },
  ),
  spell(
    'charmPerson',
    'Charm person',
    'enchantment',
    { ...sw(1), bard: 1 },
    'Makes one person your friend',
    { subschools: ['charm'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'chillTouch',
    'Chill touch',
    'necromancy',
    { ...sw(1), magus: 1 },
    'One touch/level deals 1d6 damage and 1 Str damage',
  ),
  spell(
    'colorSpray',
    'Color spray',
    'illusion',
    sw(1),
    'Knocks unconscious, blinds or stuns weak creatures',
    { subschools: ['pattern'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'command',
    'Command',
    'enchantment',
    co(1),
    'One subject obeys a one-word command for 1 round',
    {
      subschools: ['compulsion'],
      descriptors: ['language-dependent', 'mind-affecting'],
    },
  ),
  spell(
    'comprehendLanguages',
    'Comprehend languages',
    'divination',
    { ...sw(1), ...co(1), bard: 1 },
    'You understand all spoken and written languages',
  ),
  spell(
    'cureLightWounds',
    'Cure light wounds',
    'conjuration',
    { ...co(1), bard: 1, druid: 1, paladin: 1, ranger: 2 },
    'Cures 1d8 damage + 1/level (max +5)',
    { subschools: ['healing'] },
  ),
  spell(
    'detectUndead',
    'Detect undead',
    'divination',
    { ...sw(1), ...co(1), paladin: 1 },
    'Reveals undead within 60 ft.',
  ),
  spell(
    'divineFavor',
    'Divine favor',
    'evocation',
    { ...co(1), paladin: 1 },
    '+1 luck on attack and damage per three levels',
  ),
  spell(
    'endureElements',
    'Endure elements',
    'abjuration',
    { ...sw(1), ...co(1), druid: 1, paladin: 1, ranger: 1 },
    'Exist comfortably in hot or cold regions',
    { domain: { Sun: 1 } },
  ),
  spell(
    'enlargePerson',
    'Enlarge person',
    'transmutation',
    { ...sw(1), magus: 1, summoner: 1 },
    'Humanoid creature doubles in size',
  ),
  spell(
    'featherFall',
    'Feather fall',
    'transmutation',
    { ...sw(1), bard: 1 },
    'Objects or creatures fall slowly',
  ),
  spell(
    'grease',
    'Grease',
    'conjuration',
    { ...sw(1), bard: 1, magus: 1, summoner: 1 },
    'Makes a 10-ft. square or one object slippery',
    { subschools: ['creation'] },
  ),
  spell(
    'identify',
    'Identify',
    'divination',
    { ...sw(1), bard: 1, magus: 1 },
    '+10 on Spellcraft to identify magic items',
    { bloodline: { Arcane: 1 } },
  ),
  spell(
    'mageArmor',
    'Mage armor',
    'conjuration',
    { ...sw(1), summoner: 1 },
    'Gives subject +4 armor bonus',
    { subschools: ['creation'], descriptors: ['force'] },
  ),
  spell(
    'magicMissile',
    'Magic missile',
    'evocation',
    { ...sw(1), magus: 1 },
    '1d4+1 force damage; +1 missile per two levels above 1st (max 5)',
    { descriptors: ['force'] },
  ),
  spell(
    'magicWeapon',
    'Magic weapon',
    'transmutation',
    { ...sw(1), ...co(1), magus: 1, paladin: 1 },
    'Weapon gains +1 enhancement bonus',
  ),
  spell(
    'protectionFromEvil',
    'Protection from evil',
    'abjuration',
    { ...sw(1), ...co(1), paladin: 1 },
    '+2 to AC and saves, plus additional protection against evil',
    { descriptors: ['good'] },
  ),
  spell(
    'rayOfEnfeeblement',
    'Ray of enfeeblement',
    'necromancy',
    sw(1),
    'Ray deals 1d6 + 1 per two levels Str penalty',
  ),
  spell(
    'shield',
    'Shield',
    'abjuration',
    { ...sw(1), magus: 1 },
    'Invisible disc gives +4 to AC, blocks magic missiles',
    { descriptors: ['force'] },
  ),
  spell(
    'shieldOfFaith',
    'Shield of faith',
    'abjuration',
    co(1),
    'Aura grants +2 or higher deflection bonus',
  ),
  spell(
    'shockingGrasp',
    'Shocking grasp',
    'evocation',
    { ...sw(1), magus: 1 },
    'Touch delivers 1d6/level electricity damage (max 5d6)',
    { descriptors: ['electricity'] },
  ),
  spell(
    'sleep',
    'Sleep',
    'enchantment',
    { ...sw(1), bard: 1 },
    'Puts 4 HD of creatures into magical slumber',
    { subschools: ['compulsion'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'summonNaturesAlly1',
    'Summon nature’s ally I',
    'conjuration',
    { druid: 1, ranger: 1 },
    'Calls creature to fight',
    { subschools: ['summoning'] },
  ),
  spell(
    'unseenServant',
    'Unseen servant',
    'conjuration',
    { ...sw(1), bard: 1 },
    'Invisible force obeys your commands',
    { subschools: ['creation'] },
  ),
  // ------------------------------------------------------------ 2nd
  spell(
    'aid',
    'Aid',
    'enchantment',
    co(2),
    '+1 on attack rolls and saves against fear, 1d8 temporary hp + 1/level',
    { subschools: ['compulsion'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'bullsStrength',
    'Bull’s strength',
    'transmutation',
    { ...sw(2), ...co(2), druid: 2, magus: 2, paladin: 2 },
    'Subject gains +4 to Str for 1 min/level',
  ),
  spell(
    'commandUndead',
    'Command undead',
    'necromancy',
    sw(2),
    'Undead creature obeys your commands',
  ),
  spell(
    'cureModerateWounds',
    'Cure moderate wounds',
    'conjuration',
    { ...co(2), bard: 2, druid: 3, paladin: 3, ranger: 3 },
    'Cures 2d8 damage + 1/level (max +10)',
    { subschools: ['healing'] },
  ),
  spell(
    'falseLife',
    'False life',
    'necromancy',
    sw(2),
    'Gain 1d10 temporary hp + 1/level (max +10)',
  ),
  spell(
    'flamingSphere',
    'Flaming sphere',
    'evocation',
    { ...sw(2), druid: 2, magus: 2 },
    'Rolling ball of fire deals 3d6 fire damage',
    { descriptors: ['fire'] },
  ),
  spell(
    'foxsCunning',
    'Fox’s cunning',
    'transmutation',
    { ...sw(2), bard: 2, magus: 2 },
    'Subject gains +4 Int for 1 min/level',
  ),
  spell(
    'glitterdust',
    'Glitterdust',
    'conjuration',
    { ...sw(2), bard: 2 },
    'Blinds creatures, outlines invisible creatures',
    { subschools: ['creation'] },
  ),
  spell(
    'heatMetal',
    'Heat metal',
    'transmutation',
    { druid: 2 },
    'Makes metal so hot it damages those who touch it',
    { domain: { Sun: 2 }, descriptors: ['fire'] },
  ),
  spell(
    'hideousLaughter',
    'Hideous laughter',
    'enchantment',
    { ...sw(2), bard: 1 },
    'Subject loses actions for 1 round/level',
    { subschools: ['compulsion'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'holdPerson',
    'Hold person',
    'enchantment',
    { ...sw(3), ...co(2), bard: 2 },
    'Paralyzes one humanoid for 1 round/level',
    { subschools: ['compulsion'], descriptors: ['mind-affecting'] },
  ),
  spell(
    'invisibility',
    'Invisibility',
    'illusion',
    { ...sw(2), bard: 2, magus: 2, summoner: 2 },
    'Subject is invisible for 1 min/level or until it attacks',
    { bloodline: { Arcane: 2 }, subschools: ['glamer'] },
  ),
  spell(
    'lesserRestoration',
    'Lesser restoration',
    'conjuration',
    { ...co(2), druid: 2, paladin: 1 },
    'Dispels magical ability penalty or repairs 1d4 ability damage',
    { subschools: ['healing'] },
  ),
  spell(
    'mirrorImage',
    'Mirror image',
    'illusion',
    { ...sw(2), bard: 2, magus: 2, summoner: 2 },
    'Creates decoy duplicates of you',
    { subschools: ['figment'] },
  ),
  spell(
    'produceFlame',
    'Produce flame',
    'evocation',
    { druid: 1 },
    '1d6 damage + 1/level, touch or thrown',
    { domain: { Fire: 2 }, descriptors: ['fire'] },
  ),
  spell(
    'resistEnergy',
    'Resist energy',
    'abjuration',
    { ...sw(2), ...co(2), druid: 2, paladin: 2, ranger: 1 },
    'Ignores 10 (or more) points of damage per attack from one kind of energy',
  ),
  spell(
    'scorchingRay',
    'Scorching ray',
    'evocation',
    { ...sw(2), magus: 2 },
    'Ranged touch attack deals 4d6 fire damage, +1 ray per four levels (max 3)',
    { descriptors: ['fire'] },
  ),
  spell(
    'shieldOther',
    'Shield other',
    'abjuration',
    { ...co(2), paladin: 2 },
    'You take half of subject’s damage',
    { domain: { Community: 2 } },
  ),
  spell(
    'silence',
    'Silence',
    'illusion',
    { ...co(2), bard: 2 },
    'Negates sound in a 20-ft. radius',
    { subschools: ['glamer'] },
  ),
  spell(
    'spiritualWeapon',
    'Spiritual weapon',
    'evocation',
    co(2),
    'Magic weapon attacks on its own',
    { descriptors: ['force'] },
  ),
  spell(
    'web',
    'Web',
    'conjuration',
    { ...sw(2), magus: 2, summoner: 2 },
    'Fills a 20-ft.-radius spread with sticky spiderwebs',
    { subschools: ['creation'] },
  ),
  // ------------------------------------------------------------ 3rd
  spell(
    'daylight',
    'Daylight',
    'evocation',
    { ...sw(3), ...co(3), bard: 3, druid: 3, paladin: 3 },
    '60-ft. radius of bright light',
    { descriptors: ['light'] },
  ),
  spell(
    'dispelMagic',
    'Dispel magic',
    'abjuration',
    { ...sw(3), ...co(3), bard: 3, druid: 4, magus: 3, paladin: 3 },
    'Cancels one magical spell or effect',
    { bloodline: { Arcane: 3 } },
  ),
  spell(
    'fireball',
    'Fireball',
    'evocation',
    { ...sw(3), magus: 3 },
    '1d6 damage per level, 20-ft. radius',
    { domain: { Fire: 3 }, descriptors: ['fire'] },
  ),
  spell(
    'fly',
    'Fly',
    'transmutation',
    { ...sw(3), magus: 3 },
    'Subject flies at speed of 60 ft.',
  ),
  spell(
    'haste',
    'Haste',
    'transmutation',
    { ...sw(3), bard: 3, magus: 3, summoner: 2 },
    'One creature/level moves faster, +1 on attack rolls, AC and Reflex saves',
  ),
  spell(
    'lightningBolt',
    'Lightning bolt',
    'evocation',
    { ...sw(3), magus: 3 },
    'Electricity deals 1d6/level damage',
    { descriptors: ['electricity'] },
  ),
  spell(
    'magicVestment',
    'Magic vestment',
    'transmutation',
    co(3),
    'Armor or shield gains +1 enhancement per four levels',
  ),
  spell(
    'prayer',
    'Prayer',
    'enchantment',
    { ...co(3), paladin: 3 },
    'Allies +1 bonus on most rolls, enemies −1 penalty',
    {
      domain: { Community: 3 },
      subschools: ['compulsion'],
      descriptors: ['mind-affecting'],
    },
  ),
  spell(
    'searingLight',
    'Searing light',
    'evocation',
    co(3),
    'Ray deals 1d8/two levels damage, more against undead',
    { domain: { Sun: 3 }, descriptors: ['light'] },
  ),
  spell(
    'slow',
    'Slow',
    'transmutation',
    { ...sw(3), bard: 3, magus: 3 },
    'One subject/level takes only one action/round, −1 to AC, Reflex saves and attack rolls',
  ),
  spell(
    'vampiricTouch',
    'Vampiric touch',
    'necromancy',
    { ...sw(3), magus: 3 },
    'Touch deals 1d6/two levels damage; caster gains damage as hp',
  ),
  // ------------------------------------------------------------ 4th
  spell(
    'dimensionDoor',
    'Dimension door',
    'conjuration',
    { ...sw(4), bard: 4, magus: 4 },
    'Teleports you a short distance',
    { bloodline: { Arcane: 4 }, subschools: ['teleportation'] },
  ),
  spell(
    'divinePower',
    'Divine power',
    'evocation',
    co(4),
    'You gain attack bonus, +1 hp/level',
  ),
  spell(
    'fireShield',
    'Fire shield',
    'evocation',
    { ...sw(4), magus: 4 },
    'Creatures attacking you take fire damage; you’re protected from heat or cold',
    { domain: { Fire: 5, Sun: 4 }, descriptors: ['fire', 'cold'] },
  ),
  spell(
    'greaterInvisibility',
    'Greater invisibility',
    'illusion',
    { ...sw(4), bard: 4, magus: 4 },
    'As invisibility, but subject can attack and stay invisible',
    { subschools: ['glamer'] },
  ),
  spell(
    'wallOfFire',
    'Wall of fire',
    'evocation',
    { ...sw(4), druid: 5, magus: 4 },
    'Deals 2d4 fire damage out to 10 ft. and 1d4 out to 20 ft.',
    { domain: { Fire: 4 }, descriptors: ['fire'] },
  ),
];
