import type { CharacterSheetRacialProgression } from './character-sheet';

// #253's thirteen pinned racial-hd resources seed editable race definitions.
// These are supporting resources, never extra Class Levels or Catalog Entries.
export const creatureTypeProgressionSeeds = [
  {
    name: 'Aberration',
    creatureType: 'aberration',
    sourceKey: 'pf1/WiROthmRgcwDncDM',
    progression: {
      creatureType: 'Aberration',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerHitDie: 4,
      classSkills: [
        'acr',
        'clm',
        'esc',
        'fly',
        'int',
        'per',
        'spl',
        'ste',
        'sur',
        'swm',
      ],
    },
  },
  {
    name: 'Animal',
    creatureType: 'animal',
    sourceKey: 'pf1/WJqmmfXscPVpcISH',
    progression: {
      creatureType: 'Animal',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'good', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: ['acr', 'clm', 'fly', 'per', 'ste', 'swm'],
    },
  },
  {
    name: 'Construct',
    creatureType: 'construct',
    sourceKey: 'pf1/H8FbMUps5Z0gQdvV',
    progression: {
      creatureType: 'Construct',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'poor', ref: 'poor', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: [],
    },
  },
  {
    name: 'Dragon',
    creatureType: 'dragon',
    sourceKey: 'pf1/X2WLdbFFedaah6VC',
    progression: {
      creatureType: 'Dragon',
      hitDie: 12,
      bab: 'full',
      saves: { fort: 'good', ref: 'good', will: 'good' },
      skillRanksPerHitDie: 6,
      classSkills: [
        'apr',
        'blf',
        'clm',
        'crf',
        'dip',
        'fly',
        'hea',
        'int',
        'kar',
        'kdu',
        'ken',
        'kge',
        'khi',
        'klo',
        'kna',
        'kno',
        'kpl',
        'kre',
        'lin',
        'per',
        'sen',
        'spl',
        'ste',
        'sur',
        'swm',
        'umd',
      ],
    },
  },
  {
    name: 'Fey',
    creatureType: 'fey',
    sourceKey: 'pf1/0jjH2XJVd6dzlaSm',
    progression: {
      creatureType: 'Fey',
      hitDie: 6,
      bab: 'half',
      saves: { fort: 'poor', ref: 'good', will: 'good' },
      skillRanksPerHitDie: 6,
      classSkills: [
        'acr',
        'blf',
        'clm',
        'crf',
        'dip',
        'dis',
        'esc',
        'fly',
        'kge',
        'klo',
        'kna',
        'per',
        'prf',
        'sen',
        'slt',
        'ste',
        'swm',
        'umd',
      ],
    },
  },
  {
    name: 'Humanoid',
    creatureType: 'humanoid',
    sourceKey: 'pf1/S38eYYsK7pRhPbwg',
    progression: {
      creatureType: 'Humanoid',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'good', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: ['clm', 'crf', 'han', 'hea', 'pro', 'rid', 'sur'],
    },
  },
  {
    name: 'Magical Beast',
    creatureType: 'magicalBeast',
    sourceKey: 'pf1/AjUleVwKSsSaDI4N',
    progression: {
      creatureType: 'Magical Beast',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'good', ref: 'good', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: ['acr', 'clm', 'fly', 'per', 'ste', 'swm'],
    },
  },
  {
    name: 'Monstrous Humanoid',
    creatureType: 'monstrousHumanoid',
    sourceKey: 'pf1/6Uh8PAjR3BE7dult',
    progression: {
      creatureType: 'Monstrous Humanoid',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'poor', ref: 'good', will: 'good' },
      skillRanksPerHitDie: 4,
      classSkills: [
        'clm',
        'crf',
        'fly',
        'int',
        'per',
        'rid',
        'ste',
        'sur',
        'swm',
      ],
    },
  },
  {
    name: 'Ooze',
    creatureType: 'ooze',
    sourceKey: 'pf1/D1vugd9jeyAQrLVX',
    progression: {
      creatureType: 'Ooze',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'poor', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: [],
    },
  },
  {
    name: 'Outsider',
    creatureType: 'outsider',
    sourceKey: 'pf1/cV7yHt8i5YCV0ZTd',
    progression: {
      creatureType: 'Outsider',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'poor', ref: 'good', will: 'good' },
      skillRanksPerHitDie: 6,
      classSkills: ['blf', 'crf', 'kpl', 'per', 'sen', 'ste'],
    },
  },
  {
    name: 'Plant',
    creatureType: 'plant',
    sourceKey: 'pf1/AbOSfjvKMqpNihdM',
    progression: {
      creatureType: 'Plant',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'poor', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: ['per', 'ste'],
    },
  },
  {
    name: 'Undead',
    creatureType: 'undead',
    sourceKey: 'pf1/mp1Zmbx0OAzSW4oW',
    progression: {
      creatureType: 'Undead',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerHitDie: 4,
      classSkills: [
        'clm',
        'dis',
        'fly',
        'int',
        'kar',
        'kre',
        'per',
        'sen',
        'spl',
        'ste',
      ],
    },
  },
  {
    name: 'Vermin',
    creatureType: 'vermin',
    sourceKey: 'pf1/g3gX00gTvJU478ju',
    progression: {
      creatureType: 'Vermin',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'poor', will: 'poor' },
      skillRanksPerHitDie: 2,
      classSkills: [],
    },
  },
] as const satisfies readonly {
  name: string;
  creatureType: string;
  sourceKey: string;
  progression: CharacterSheetRacialProgression;
}[];

export function findRacialProgression(creatureType: string) {
  const seed = creatureTypeProgressionSeeds.find(
    (entry) => entry.creatureType === creatureType,
  );
  return seed
    ? {
        ...seed.progression,
        saves: { ...seed.progression.saves },
        classSkills: [...seed.progression.classSkills],
      }
    : undefined;
}
