import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  character: defineTable({
    name: v.string(),
    ownerId: v.number(),
    campaignId: v.number(),
    description: v.string(),
  }),
  campaign: defineTable({
    name: v.string(),
    campaignId: v.number(),
    ownerId: v.string(),
    description: v.string(),
  }),
  spell: defineTable({
    name: v.string(),
    school: v.string(),
    subschool: v.string(),
    descriptor: v.string(),
    casting_time: v.string(),
    components: v.string(),
    costly_components: v.boolean(),
    range: v.string(),
    area: v.string(),
    effect: v.string(),
    targets: v.string(),
    duration: v.string(),
    dismissible: v.boolean(),
    shapeable: v.boolean(),
    saving_throw: v.string(),
    spell_resistance: v.string(),
    description: v.string(),
    description_formatted: v.string(),
    source: v.string(),
    full_text: v.string(),
    verbal: v.boolean(),
    somatic: v.boolean(),
    material: v.boolean(),
    focus: v.boolean(),
    divine_focus: v.boolean(),
    sorcerer: v.union(v.number(), v.null()),
    wizard: v.union(v.number(), v.null()),
    cleric: v.union(v.number(), v.null()),
    druid: v.union(v.number(), v.null()),
    ranger: v.union(v.number(), v.null()),
    bard: v.union(v.number(), v.null()),
    paladin: v.union(v.number(), v.null()),
    alchemist: v.union(v.number(), v.null()),
    summoner: v.union(v.number(), v.null()),
    witch: v.union(v.number(), v.null()),
    inquisitor: v.union(v.number(), v.null()),
    oracle: v.union(v.number(), v.null()),
    antipaladin: v.union(v.number(), v.null()),
    magus: v.union(v.number(), v.null()),
    adept: v.union(v.number(), v.null()),
    deity: v.string(),
    SLA_Level: v.number(),
    domain: v.string(),
    short_description: v.string(),
    acid: v.boolean(),
    air: v.boolean(),
    chaotic: v.boolean(),
    cold: v.boolean(),
    curse: v.boolean(),
    darkness: v.boolean(),
    death: v.boolean(),
    disease: v.boolean(),
    earth: v.boolean(),
    electricity: v.boolean(),
    emotion: v.boolean(),
    evil: v.boolean(),
    fear: v.boolean(),
    fire: v.boolean(),
    force: v.boolean(),
    good: v.boolean(),
    language_dependent: v.boolean(),
    lawful: v.boolean(),
    light: v.boolean(),
    mind_affecting: v.boolean(),
    pain: v.boolean(),
    poison: v.boolean(),
    shadow: v.boolean(),
    sonic: v.boolean(),
    water: v.boolean(),
    linktext: v.string(),
    id: v.number(),
    material_costs: v.union(v.number(), v.null()),
    bloodline: v.string(),
    patron: v.string(),
    mythic_text: v.string(),
    augmented: v.string(),
    mythic: v.boolean(),
    bloodrager: v.union(v.number(), v.null()),
    shaman: v.union(v.number(), v.null()),
    psychic: v.union(v.number(), v.null()),
    medium: v.union(v.number(), v.null()),
    mesmerist: v.union(v.number(), v.null()),
    occultist: v.union(v.number(), v.null()),
    spiritualist: v.union(v.number(), v.null()),
    skald: v.union(v.number(), v.null()),
    investigator: v.union(v.number(), v.null()),
    hunter: v.union(v.number(), v.null()),
    ruse: v.boolean(),
    draconic: v.boolean(),
    meditative: v.boolean(),
    summoner_unchained: v.union(v.number(), v.null()),
  }),
});
