import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export const spellValidator = v.object({
  name: v.string(),
  spellLevel: v.string(),
  school: v.string(),
  subschool: v.string(),
  descriptor: v.string(),
  castingTime: v.string(),
  components: v.string(),
  hasCostlyComponents: v.boolean(),
  range: v.string(),
  area: v.string(),
  effect: v.string(),
  targets: v.string(),
  duration: v.string(),
  dismissible: v.boolean(),
  shapeable: v.boolean(),
  savingThrow: v.string(),
  spellResistance: v.string(),
  description: v.string(),
  descriptionFormatted: v.string(),
  source: v.string(),
  fullText: v.string(),
  verbal: v.boolean(),
  somatic: v.boolean(),
  material: v.boolean(),
  requiresFocus: v.boolean(),
  requiresDivineFocus: v.boolean(),
  sorcerer: v.union(v.number(), v.null()),
  wizard: v.union(v.number(), v.null()),
  cleric: v.union(v.number(), v.null()),
  druid: v.union(v.number(), v.null()),
  ranger: v.union(v.number(), v.null()),
  bard: v.union(v.number(), v.null()),
  paladin: v.union(v.number(), v.null()),
  alchemist: v.union(v.number(), v.null()),
  summoner: v.union(v.number(), v.null()),
  witch: v.union(v.number(), v.null()),
  inquisitor: v.union(v.number(), v.null()),
  oracle: v.union(v.number(), v.null()),
  antipaladin: v.union(v.number(), v.null()),
  magus: v.union(v.number(), v.null()),
  adept: v.union(v.number(), v.null()),
  deity: v.string(),
  SLALevel: v.union(v.number(), v.null()),
  domain: v.string(),
  shortDescription: v.string(),
  acid: v.boolean(),
  air: v.boolean(),
  chaotic: v.boolean(),
  cold: v.boolean(),
  curse: v.boolean(),
  darkness: v.boolean(),
  death: v.boolean(),
  disease: v.boolean(),
  earth: v.boolean(),
  electricity: v.boolean(),
  emotion: v.boolean(),
  evil: v.boolean(),
  fear: v.boolean(),
  fire: v.boolean(),
  force: v.boolean(),
  good: v.boolean(),
  languageDependent: v.boolean(),
  lawful: v.boolean(),
  light: v.boolean(),
  mindAffecting: v.boolean(),
  pain: v.boolean(),
  poison: v.boolean(),
  shadow: v.boolean(),
  sonic: v.boolean(),
  water: v.boolean(),
  linkText: v.union(v.string(), v.null()),
  id: v.number(),
  materialCosts: v.union(v.number(), v.null()),
  bloodline: v.string(),
  patron: v.string(),
  mythicText: v.string(),
  augmented: v.string(),
  mythic: v.boolean(),
  bloodrager: v.union(v.number(), v.null()),
  shaman: v.union(v.number(), v.null()),
  psychic: v.union(v.number(), v.null()),
  medium: v.union(v.number(), v.null()),
  mesmerist: v.union(v.number(), v.null()),
  occultist: v.union(v.number(), v.null()),
  spiritualist: v.union(v.number(), v.null()),
  skald: v.union(v.number(), v.null()),
  investigator: v.union(v.number(), v.null()),
  hunter: v.union(v.number(), v.null()),
  ruse: v.boolean(),
  draconic: v.boolean(),
  meditative: v.boolean(),
  summonerUnchained: v.union(v.number(), v.null()),
})

export const characterValidator = v.object({
  name: v.string(),
  ownerId: v.number(),
  campaignId: v.id("campaign"),
  description: v.string(),
})

export const campaignValidator = v.object({
  name: v.string(),
  ownerId: v.string(),
  organizationId: v.optional(v.string()),
  description: v.string(),
})

export const roles = v.union(v.literal("admin"), v.literal("member"));

export default defineSchema({
  character: defineTable(characterValidator),
  campaign: defineTable(campaignValidator)
    .index("by_organization", ["organizationId"]),
  spell: defineTable(spellValidator)
    .index("by_name", ["name"]),
  characterSpell: defineTable(v.object({
    characterId: v.id("character"),
    spellId: v.id("spell")
  }))
    .index("characterId", ["characterId"])
    .index("spellId_characterId", ["spellId", "characterId"]),
  user: defineTable({
    tokenIdentifier: v.string(),
    name: v.optional(v.string()),
    image: v.optional(v.string()),
    orgIds: v.array(
      v.object({
        orgId: v.string(),
        role: roles,
      })
    ),
  }).index("by_tokenIdentifier", ["tokenIdentifier"]),
});
