import { findReviewedClassCasting } from '../../src/lib/character-sheet-casting-tables';
import type { Doc, Id } from '../_generated/dataModel';

// Representative prepared-sheet seed data, not a curated Catalog Release.
// Pathfinder RPG Core Rulebook class tables: cleric p. 40, fighter p. 56,
// rogue p. 68, sorcerer pp. 70–73 and wizard p. 80; Advanced Player’s Guide
// alchemist pp. 26–27 and witch pp. 65–67. Feature curation is tracked separately.
export const representativeClassCatalog = [
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '56' }],
    stacksWithItself: false,
    name: 'Fighter',
    ruleIdentity: 'fighter',
    proficiencies: [
      { category: 'simple' },
      { category: 'martial' },
      { category: 'light' },
      { category: 'medium' },
      { category: 'heavy' },
      { category: 'shield' },
      { category: 'towerShield' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      classKind: 'base',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'good', ref: 'poor', will: 'poor' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.clm',
        'skill.crf',
        'skill.han',
        'skill.int',
        'skill.kdu',
        'skill.ken',
        'skill.pro',
        'skill.rid',
        'skill.sur',
        'skill.swm',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '80' }],
    stacksWithItself: false,
    name: 'Wizard',
    ruleIdentity: 'wizard',
    proficiencies: [
      { baseType: 'club' },
      { baseType: 'dagger' },
      { baseType: 'heavy crossbow' },
      { baseType: 'light crossbow' },
      { baseType: 'quarterstaff' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('wizard'),
      classKind: 'base',
      hitDie: 6,
      bab: 'half',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.apr',
        'skill.crf',
        'skill.fly',
        'skill.kar',
        'skill.kdu',
        'skill.ken',
        'skill.kge',
        'skill.khi',
        'skill.klo',
        'skill.kna',
        'skill.kno',
        'skill.kpl',
        'skill.kre',
        'skill.lin',
        'skill.pro',
        'skill.spl',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '68' }],
    stacksWithItself: false,
    name: 'Rogue',
    ruleIdentity: 'rogue',
    proficiencies: [
      { category: 'simple' },
      { baseType: 'hand crossbow' },
      { baseType: 'rapier' },
      { baseType: 'sap' },
      { baseType: 'shortbow' },
      { baseType: 'short sword' },
      { category: 'light' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      classKind: 'base',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'good', will: 'poor' },
      skillRanksPerLevel: 8,
      classSkills: [
        'skill.acr',
        'skill.apr',
        'skill.blf',
        'skill.clm',
        'skill.crf',
        'skill.dip',
        'skill.dev',
        'skill.dis',
        'skill.esc',
        'skill.int',
        'skill.kdu',
        'skill.klo',
        'skill.lin',
        'skill.per',
        'skill.prf',
        'skill.pro',
        'skill.sen',
        'skill.slt',
        'skill.ste',
        'skill.swm',
        'skill.umd',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '40' }],
    stacksWithItself: false,
    name: 'Cleric',
    ruleIdentity: 'cleric',
    proficiencies: [
      { category: 'simple' },
      { category: 'light' },
      { category: 'medium' },
      { category: 'shield' },
      { choice: true },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('cleric'),
      classKind: 'base',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.apr',
        'skill.crf',
        'skill.dip',
        'skill.hea',
        'skill.kar',
        'skill.khi',
        'skill.kno',
        'skill.kpl',
        'skill.kre',
        'skill.lin',
        'skill.pro',
        'skill.sen',
        'skill.spl',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '70–73' }],
    stacksWithItself: false,
    name: 'Sorcerer',
    ruleIdentity: 'sorcerer',
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('sorcerer'),
      classKind: 'base',
      hitDie: 6,
      bab: 'half',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.apr',
        'skill.blf',
        'skill.crf',
        'skill.fly',
        'skill.int',
        'skill.kar',
        'skill.pro',
        'skill.spl',
        'skill.umd',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [
      { book: 'Pathfinder RPG Advanced Player’s Guide', pages: '26–27' },
    ],
    stacksWithItself: false,
    name: 'Alchemist',
    ruleIdentity: 'alchemist',
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('alchemist'),
      classKind: 'base',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'good', will: 'poor' },
      skillRanksPerLevel: 4,
      classSkills: [
        'skill.apr',
        'skill.crf',
        'skill.dev',
        'skill.fly',
        'skill.han',
        'skill.hea',
        'skill.kar',
        'skill.kna',
        'skill.per',
        'skill.pro',
        'skill.slt',
        'skill.spl',
        'skill.sur',
        'skill.umd',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [
      { book: 'Pathfinder RPG Advanced Player’s Guide', pages: '65–67' },
    ],
    stacksWithItself: false,
    name: 'Witch',
    ruleIdentity: 'witch',
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('witch'),
      classKind: 'base',
      hitDie: 6,
      bab: 'half',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.crf',
        'skill.fly',
        'skill.hea',
        'skill.int',
        'skill.kar',
        'skill.khi',
        'skill.kna',
        'skill.kpl',
        'skill.pro',
        'skill.spl',
        'skill.umd',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
] satisfies Omit<
  Extract<Doc<'catalogEntry'>, { detail: { kind: 'class' } }>,
  '_id' | '_creationTime' | 'scope' | 'characterId'
>[];

// Exact feature rows from CRB Tables 3-9 and 3-13, through class level 20.
// Keys are materialized after all feature definitions have durable document IDs.
export const representativeClassFeatureSchedules: Record<
  string,
  { classLevel: number; catalogEntryId: string }[]
> = {
  fighter: [
    { classLevel: 1, catalogEntryId: 'fighter-bonus-feat-1' },
    ...[2, 4, 6, 8, 10, 12, 14, 16, 18, 20].map((classLevel) => ({
      classLevel,
      catalogEntryId: `fighter-bonus-feat-${classLevel}`,
    })),
    ...[2, 6, 10, 14, 18].map((classLevel) => ({
      classLevel,
      catalogEntryId: `fighter-bravery-${classLevel}`,
    })),
    ...[3, 7, 11, 15].map((classLevel) => ({
      classLevel,
      catalogEntryId: `fighter-armor-training-${classLevel}`,
    })),
    ...[5, 9, 13, 17].map((classLevel) => ({
      classLevel,
      catalogEntryId: `fighter-weapon-training-${classLevel}`,
    })),
    { classLevel: 19, catalogEntryId: 'fighter-armor-mastery' },
    { classLevel: 20, catalogEntryId: 'fighter-weapon-mastery' },
  ].sort((left, right) => left.classLevel - right.classLevel),
  rogue: [
    ...[1, 3, 5, 7, 9, 11, 13, 15, 17, 19].map((classLevel) => ({
      classLevel,
      catalogEntryId: `rogue-sneak-attack-${classLevel}`,
    })),
    { classLevel: 1, catalogEntryId: 'rogue-trapfinding' },
    { classLevel: 2, catalogEntryId: 'rogue-evasion' },
    ...[2, 4, 6, 8, 10, 12, 14, 16, 18, 20].map((classLevel) => ({
      classLevel,
      catalogEntryId: `rogue-talent-${classLevel}`,
    })),
    ...[3, 6, 9, 12, 15, 18].map((classLevel) => ({
      classLevel,
      catalogEntryId: `rogue-trap-sense-${classLevel}`,
    })),
    { classLevel: 4, catalogEntryId: 'rogue-uncanny-dodge' },
    { classLevel: 8, catalogEntryId: 'rogue-improved-uncanny-dodge' },
    { classLevel: 10, catalogEntryId: 'rogue-advanced-talents' },
    { classLevel: 20, catalogEntryId: 'rogue-master-strike' },
  ].sort((left, right) => left.classLevel - right.classLevel),
};

export function materializeRepresentativeClassFeatureSchedule(
  classIdentity: string,
  idForKey: (key: string) => Id<'catalogEntry'>,
): { classLevel: number; catalogEntryId: Id<'catalogEntry'> }[] {
  return (representativeClassFeatureSchedules[classIdentity] ?? []).map(
    ({ classLevel, catalogEntryId }) => ({
      classLevel,
      catalogEntryId: idForKey(catalogEntryId),
    }),
  );
}
