import type { CharacterSheetCatalogEntry } from '../../src/lib/character-sheet';

// Representative prepared-sheet Base Items, not a curated Catalog Release.
// Pathfinder RPG Core Rulebook, Table 6–4 (pp. 142–143) and weapon descriptions
// (pp. 144–149). Damage dice are the printed Medium-size values.
export const representativeWeaponCatalog = [
  {
    name: 'Longsword',
    ruleIdentity: 'longsword',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'longsword',
        proficiency: 'martial',
        handedness: 'oneHanded',
        attackType: 'melee',
        dice: '1d8',
        damageTypes: ['slashing'],
        threat: 19,
        mult: 2,
        strengthDamage: 'melee',
      },
    },
  },
  {
    name: 'Greatsword',
    ruleIdentity: 'greatsword',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'greatsword',
        proficiency: 'martial',
        handedness: 'twoHanded',
        attackType: 'melee',
        dice: '2d6',
        damageTypes: ['slashing'],
        threat: 19,
        mult: 2,
        strengthDamage: 'melee',
      },
    },
  },
  {
    name: 'Dagger',
    ruleIdentity: 'dagger',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'dagger',
        proficiency: 'simple',
        handedness: 'light',
        attackType: 'melee',
        dice: '1d4',
        damageTypes: ['piercing', 'slashing'],
        threat: 19,
        mult: 2,
        thrown: true,
        thrownRangeIncrement: 10,
        strengthDamage: 'melee',
      },
    },
  },
  {
    name: 'Spear',
    ruleIdentity: 'spear',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'spear',
        proficiency: 'simple',
        handedness: 'twoHanded',
        attackType: 'melee',
        dice: '1d8',
        damageTypes: ['piercing'],
        threat: 20,
        mult: 3,
        thrown: true,
        thrownRangeIncrement: 20,
        strengthDamage: 'melee',
      },
    },
  },
  {
    name: 'Longbow',
    ruleIdentity: 'longbow',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143, 147' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'longbow',
        proficiency: 'martial',
        handedness: 'twoHanded',
        attackType: 'ranged',
        dice: '1d8',
        damageTypes: ['piercing'],
        threat: 20,
        mult: 3,
        rangeIncrement: 100,
        strengthDamage: 'bow',
      },
    },
  },
  {
    name: 'Composite longbow (+2 Strength)',
    ruleIdentity: 'composite-longbow-2',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143, 147' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'composite longbow',
        proficiency: 'martial',
        handedness: 'twoHanded',
        attackType: 'ranged',
        dice: '1d8',
        damageTypes: ['piercing'],
        threat: 20,
        mult: 3,
        rangeIncrement: 110,
        strengthDamage: 'compositeBow',
        strengthRating: 2,
      },
    },
  },
  {
    name: 'Light crossbow',
    ruleIdentity: 'light-crossbow',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143, 145' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'light crossbow',
        proficiency: 'simple',
        handedness: 'twoHanded',
        attackType: 'ranged',
        dice: '1d8',
        damageTypes: ['piercing'],
        threat: 19,
        mult: 2,
        rangeIncrement: 80,
        strengthDamage: 'crossbow',
      },
    },
  },
  {
    name: 'Sling',
    ruleIdentity: 'sling',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143, 149' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'sling',
        proficiency: 'simple',
        handedness: 'oneHanded',
        attackType: 'ranged',
        dice: '1d4',
        damageTypes: ['bludgeoning'],
        threat: 20,
        mult: 2,
        rangeIncrement: 50,
        strengthDamage: 'sling',
      },
    },
  },
  {
    name: 'Bastard sword',
    ruleIdentity: 'bastard-sword',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '142–143, 145' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'bastard sword',
        proficiency: 'exotic',
        handedness: 'oneHanded',
        attackType: 'melee',
        dice: '1d10',
        damageTypes: ['slashing'],
        threat: 19,
        mult: 2,
        strengthDamage: 'melee',
      },
    },
  },
  {
    name: 'Gnome hooked hammer',
    ruleIdentity: 'gnome-hooked-hammer',
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '143, 147' }],
    modifiers: [],
    detail: {
      kind: 'item',
      consumable: false,
      weapon: {
        baseType: 'gnome hooked hammer',
        proficiency: 'exotic',
        handedness: 'twoHanded',
        attackType: 'melee',
        dice: '1d8',
        damageTypes: ['bludgeoning'],
        threat: 20,
        mult: 3,
        strengthDamage: 'melee',
        otherEnd: {
          dice: '1d6',
          damageTypes: ['piercing'],
          threat: 20,
          mult: 4,
        },
      },
    },
  },
] as const satisfies readonly (Omit<CharacterSheetCatalogEntry, '_id'> & {
  sources: readonly { book: string; pages: string }[];
})[];
