import { findReviewedClassCasting } from '../../src/lib/character-sheet-casting-tables';
import type { Doc } from '../_generated/dataModel';

// Representative prepared-sheet seed data, not a curated Catalog Release.
// Pathfinder RPG Core Rulebook class tables: cleric p. 40, fighter p. 56,
// rogue p. 68 and wizard p. 80. Feature curation is tracked separately.
export const representativeClassCatalog = [
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '56' }],
    stacksWithItself: false,
    name: 'Fighter',
    ruleIdentity: 'fighter',
    proficiencies: [
      { category: 'simple' },
      { category: 'martial' },
      { category: 'light' },
      { category: 'medium' },
      { category: 'heavy' },
      { category: 'shield' },
      { category: 'towerShield' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      classKind: 'base',
      hitDie: 10,
      bab: 'full',
      saves: { fort: 'good', ref: 'poor', will: 'poor' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.clm',
        'skill.crf',
        'skill.han',
        'skill.int',
        'skill.kdu',
        'skill.ken',
        'skill.pro',
        'skill.rid',
        'skill.sur',
        'skill.swm',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '80' }],
    stacksWithItself: false,
    name: 'Wizard',
    ruleIdentity: 'wizard',
    proficiencies: [
      { baseType: 'club' },
      { baseType: 'dagger' },
      { baseType: 'heavy crossbow' },
      { baseType: 'light crossbow' },
      { baseType: 'quarterstaff' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('wizard'),
      classKind: 'base',
      hitDie: 6,
      bab: 'half',
      saves: { fort: 'poor', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.apr',
        'skill.crf',
        'skill.fly',
        'skill.kar',
        'skill.kdu',
        'skill.ken',
        'skill.kge',
        'skill.khi',
        'skill.klo',
        'skill.kna',
        'skill.kno',
        'skill.kpl',
        'skill.kre',
        'skill.lin',
        'skill.pro',
        'skill.spl',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '68' }],
    stacksWithItself: false,
    name: 'Rogue',
    ruleIdentity: 'rogue',
    proficiencies: [
      { category: 'simple' },
      { baseType: 'hand crossbow' },
      { baseType: 'rapier' },
      { baseType: 'sap' },
      { baseType: 'shortbow' },
      { baseType: 'short sword' },
      { category: 'light' },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      classKind: 'base',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'poor', ref: 'good', will: 'poor' },
      skillRanksPerLevel: 8,
      classSkills: [
        'skill.acr',
        'skill.apr',
        'skill.blf',
        'skill.clm',
        'skill.crf',
        'skill.dip',
        'skill.dev',
        'skill.dis',
        'skill.esc',
        'skill.int',
        'skill.kdu',
        'skill.klo',
        'skill.lin',
        'skill.per',
        'skill.prf',
        'skill.pro',
        'skill.sen',
        'skill.slt',
        'skill.ste',
        'skill.swm',
        'skill.umd',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
  {
    sources: [{ book: 'Pathfinder RPG Core Rulebook', pages: '40' }],
    stacksWithItself: false,
    name: 'Cleric',
    ruleIdentity: 'cleric',
    proficiencies: [
      { category: 'simple' },
      { category: 'light' },
      { category: 'medium' },
      { category: 'shield' },
      { choice: true },
    ],
    modifiers: [],
    detail: {
      kind: 'class',
      casting: findReviewedClassCasting('cleric'),
      classKind: 'base',
      hitDie: 8,
      bab: 'threeQuarters',
      saves: { fort: 'good', ref: 'poor', will: 'good' },
      skillRanksPerLevel: 2,
      classSkills: [
        'skill.apr',
        'skill.crf',
        'skill.dip',
        'skill.hea',
        'skill.kar',
        'skill.khi',
        'skill.kno',
        'skill.kpl',
        'skill.kre',
        'skill.lin',
        'skill.pro',
        'skill.sen',
        'skill.spl',
      ],
      featuresByLevel: [],
      picksByLevel: [],
    },
  },
] satisfies Omit<
  Extract<Doc<'catalogEntry'>, { detail: { kind: 'class' } }>,
  '_id' | '_creationTime' | 'scope' | 'characterId'
>[];
